// from o30_aa o30_ab
let columns = ["RabbinicTerm","Term(English)","PhraseContext","PhraseContext (English)"];
let data = [
{word:"מותר",meaning:"Permitted",phrase:"מותר לעשות מלאכה זו בשבת",phraseMeaning:"It is permitted to do this work on Shabbat"},
{word:"דמי",meaning:"It is similar to",phrase:"הא דמי להא דאמרינן בפרק קמא",phraseMeaning:"This is similar to what we said in the first chapter"},
{word:"הכי",meaning:"Thus",phrase:"הכי גרסינן במתניתא",phraseMeaning:"This is how we learn it in the Mishnah"},
{word:"מידי",meaning:"Something like",phrase:"מידי דהוה אכל הנך דרבנן",phraseMeaning:"Something like all those [cases] of the Rabbis"},
{word:"סוף דבר",meaning:"The conclusion",phrase:"סוף דבר הכל צפוי והרשות נתונה",phraseMeaning:"The conclusion is everything is foreseen yet free will is given"},
{word:"א״ע",meaning:"(את עצמו/ה) Itself/oneself",phrase:"חיבק א״ע מרוב שמחה",phraseMeaning:"He hugged himself from joy"},
{word:"לא שנא",meaning:"It makes no difference",phrase:"לא שנא איש ואשה בדבר זה",phraseMeaning:"It makes no difference [between] man and woman in this matter"},
{word:"הואיל",meaning:"Since",phrase:" הואיל וטמא טמא",phraseMeaning:"Since he declared it (or somehow made it) impure, it is (thus) impure"},
{word:"גמרא",meaning:"Gemara",phrase:"גמרא: מנא הני מילי?",phraseMeaning:"The Gemara asks: From where do we derive these matters?"},
{word:"בודאי",meaning:"Certainly",phrase:"בודאי שהדבר צריך יון נוסף",phraseMeaning:"Certainly this matter requires further examination"},
{word:"סטרא אחרא",meaning:"The Other [wild/evil] Side",phrase:" מסטרא אחרא זה",phraseMeaning:"This is from the other perspective"},
{word:"ג״כ",meaning:"(גם כן) Also",phrase:"הדין נוהג בגוים ג״כ",phraseMeaning:"This law applies to non-Jews as well"},
{word:"משא״כ",meaning:"(מה שאין כן) Which is not the case",phrase:"בשבת אסור לעשות מלאכה משא״כ בחול",phraseMeaning:"On Sabbath it is forbidden to do work"},
{word:"אלא מאי",meaning:"But rather what?",phrase:"אלא מאי איכא למימר?",phraseMeaning:"But rather what is there to say?"},
{word:"יחוד",meaning:"Unification",phrase:"יחוד השם הוא תכלית כל המצוות",phraseMeaning:"The unification of God's name is the purpose of all commandments"},
{word:"אע״פ",meaning:"(אף על פי) Even though",phrase:"אע״פ כן צריך לברך עליו",phraseMeaning:" Even though this is so one needs to recite a blessing over it"},
{word:"על פי",meaning:"According to",phrase:"על פי הדברים האלה כרתי אתכם ברית",phraseMeaning:"According to these words I have made a covenant with you"},
{word:"רישא",meaning:"The beginning/top",phrase:"רישא דמתניתא קתני הכי",phraseMeaning:"The beginning of the Mishnah teaches thus"},
{word:"מנא",meaning:"From where?",phrase:"מנא לן דבעי כוונה?",phraseMeaning:"From where do we [know] that intention is required?"},
{word:"פטור",meaning:"Exempt",phrase:"פטור מן התפילה בעת הדחק",phraseMeaning:"Exempt from prayer in times of distress"},
{word:"פליג",meaning:"Argue",phrase:" פליג עליה",phraseMeaning:"He disagrees with him"},
{word:"אהבת השם",meaning:"Love of God",phrase:"העבודה צריכה להיות מתוך אהבת השם ויראתו",phraseMeaning:"Service must be performed out of love of God and fear of Him"},
{word:"ותו",meaning:"And furthermore; and more",phrase:"ותו לא והא קמ״ל",phraseMeaning:"And no more!? But behold, it comes to teach..."},
{word:"הלכתא",meaning:"(Aramaic) The law",phrase:"הלכתא כוותיה דרבי יהושע",phraseMeaning:"The law follows Rabbi Yehoshua"},
{word:"היינו",meaning:"Is equal to; that is",phrase:" היינו דאמר רבא",phraseMeaning:"This is the same as what Rava said"},
{word:"אמנם",meaning:"Indeed",phrase:" אמנם הכא שאני",phraseMeaning:"However here it is different"},
{word:"איתא",meaning:"There is",phrase:" איתא בברייתא",phraseMeaning:"It is taught in a baraita"},
{word:"לאפוקי",meaning:"To exclude",phrase:"תנא בתרא הוא דאתא לאפוקי",phraseMeaning:"It is the last Tanna that he comes to exclude / ...Tanna that comes to exclude it"},
{word:"הכי נמי",meaning:"It is really so",phrase:"הכי נמי דאמר רב אשי",phraseMeaning:"It is really as Rav Ashi said"},
{word:"תיקו",meaning:"Let it stand [unresolved]",phrase:"תיקו עד שיבא אליהו ויתרץ כל הקושיות",phraseMeaning:"Let it stand until Elijah comes and resolves all difficulties"}
];
