// from o30_aa o30_ab
let columns = ["RabbinicTerm","Term(English)","PhraseContext","PhraseContext (English)"];
let data = [
{word:"סטרא אחרא",meaning:"The Other [wild/evil] Side",phrase:" מסטרא אחרא זה",phraseMeaning:"This is from the other perspective"},
{word:"בודאי",meaning:"Certainly",phrase:"בודאי שהדבר צריך יון נוסף",phraseMeaning:"Certainly this matter requires further examination"},
{word:"הכי נמי",meaning:"It is really so",phrase:"הכי נמי דאמר רב אשי",phraseMeaning:"It is really as Rav Ashi said"},
{word:"אע״פ",meaning:"(אף על פי) Even though",phrase:"אע״פ כן צריך לברך עליו",phraseMeaning:" Even though this is so one needs to recite a blessing over it"},
{word:"איתא",meaning:"There is",phrase:" איתא בברייתא",phraseMeaning:"It is taught in a baraita"},
{word:"על פי",meaning:"According to",phrase:"על פי הדברים האלה כרתי אתכם ברית",phraseMeaning:"According to these words I have made a covenant with you"},
{word:"רישא",meaning:"The beginning/top",phrase:"רישא דמתניתא קתני הכי",phraseMeaning:"The beginning of the Mishnah teaches thus"},
{word:"פליג",meaning:"Argue",phrase:" פליג עליה",phraseMeaning:"He disagrees with him"},
{word:"משא״כ",meaning:"(מה שאין כן) Which is not the case",phrase:"בשבת אסור לעשות מלאכה משא״כ בחול",phraseMeaning:"On Sabbath it is forbidden to do work"},
{word:"לאפוקי",meaning:"To exclude",phrase:"תנא בתרא הוא דאתא לאפוקי",phraseMeaning:"It is the last Tanna that he comes to exclude / ...Tanna that comes to exclude it"},
{word:"א״ע",meaning:"(את עצמו/ה) Itself/oneself",phrase:"חיבק א״ע מרוב שמחה",phraseMeaning:"He hugged himself from joy"},
{word:"דמי",meaning:"It is similar to",phrase:"הא דמי להא דאמרינן בפרק קמא",phraseMeaning:"This is similar to what we said in the first chapter"},
{word:"גמרא",meaning:"Gemara",phrase:"גמרא: מנא הני מילי?",phraseMeaning:"The Gemara asks: From where do we derive these matters?"},
{word:"יחוד",meaning:"Unification",phrase:"יחוד השם הוא תכלית כל המצוות",phraseMeaning:"The unification of God's name is the purpose of all commandments"},
{word:"הלכתא",meaning:"(Aramaic) The law",phrase:"הלכתא כוותיה דרבי יהושע",phraseMeaning:"The law follows Rabbi Yehoshua"},
{word:"ותו",meaning:"And furthermore; and more",phrase:"ותו לא והא קמ״ל",phraseMeaning:"And no more!? But behold, it comes to teach..."},
{word:"סוף דבר",meaning:"The conclusion",phrase:"סוף דבר הכל צפוי והרשות נתונה",phraseMeaning:"The conclusion is everything is foreseen yet free will is given"},
{word:"מותר",meaning:"Permitted",phrase:"מותר לעשות מלאכה זו בשבת",phraseMeaning:"It is permitted to do this work on Shabbat"},
{word:"אלא מאי",meaning:"But rather what?",phrase:"אלא מאי איכא למימר?",phraseMeaning:"But rather what is there to say?"},
{word:"אהבת השם",meaning:"Love of God",phrase:"העבודה צריכה להיות מתוך אהבת השם ויראתו",phraseMeaning:"Service must be performed out of love of God and fear of Him"},
{word:"הואיל",meaning:"Since",phrase:" הואיל וטמא טמא",phraseMeaning:"Since he declared it (or somehow made it) impure, it is (thus) impure"},
{word:"אמנם",meaning:"Indeed",phrase:" אמנם הכא שאני",phraseMeaning:"However here it is different"},
{word:"מנא",meaning:"From where?",phrase:"מנא לן דבעי כוונה?",phraseMeaning:"From where do we [know] that intention is required?"},
{word:"מידי",meaning:"Something like",phrase:"מידי דהוה אכל הנך דרבנן",phraseMeaning:"Something like all those [cases] of the Rabbis"},
{word:"תיקו",meaning:"Let it stand [unresolved]",phrase:"תיקו עד שיבא אליהו ויתרץ כל הקושיות",phraseMeaning:"Let it stand until Elijah comes and resolves all difficulties"},
{word:"פטור",meaning:"Exempt",phrase:"פטור מן התפילה בעת הדחק",phraseMeaning:"Exempt from prayer in times of distress"},
{word:"ג״כ",meaning:"(גם כן) Also",phrase:"הדין נוהג בגוים ג״כ",phraseMeaning:"This law applies to non-Jews as well"},
{word:"לא שנא",meaning:"It makes no difference",phrase:"לא שנא איש ואשה בדבר זה",phraseMeaning:"It makes no difference [between] man and woman in this matter"},
{word:"היינו",meaning:"Is equal to; that is",phrase:" היינו דאמר רבא",phraseMeaning:"This is the same as what Rava said"},
{word:"הכי",meaning:"Thus",phrase:"הכי גרסינן במתניתא",phraseMeaning:"This is how we learn it in the Mishnah"},
{word:"לאו הכי",meaning:"Not so",phrase:"לאו הכי נמי אסור",phraseMeaning:"Not so it is also forbidden"},
{word:"גרסינן",meaning:"This is the version that we use",phrase:" הכי גרסינן",phraseMeaning:"Thus we learn (ie., we use this version) "},
{word:"ספירות",meaning:"Divine emanations",phrase:"עשר ספירות בלימה הן יסוד כל הבריאה",phraseMeaning:"Ten sefirot without substance are the foundation of all creation"},
{word:"מה לי",meaning:"What's it to me? What difference to me",phrase:" מה לי זה ומה לי זה",phraseMeaning:"What difference is there between this and that?"},
{word:"כגון",meaning:"For example",phrase:"כגון תפילין ומזוזה ומצוות אחרות",phraseMeaning:"For example tefillin and mezuzah and other commandments"},
{word:"חידוש",meaning:"Novel interpretation",phrase:"חידוש גדול חידש לנו הבעש״ט",phraseMeaning:"The Ba'al Shem Tov innovated a great novel teaching for us"},
{word:"התם",meaning:"There",phrase:" התם איכא למימר",phraseMeaning:"There one can say"},
{word:"רמי",meaning:"Throw a contradiction or a challenge",phrase:" רמי בר חמא",phraseMeaning:"Bar Chama raised an objection"},
{word:"תנא",meaning:"(Early period) teacher",phrase:"תנא בתרא הוא דאתא לאפוקי",phraseMeaning:"It is the last Tanna that he comes to exclude / ...Tanna that comes to exclude it"},
{word:"איכא",meaning:"There is",phrase:"איכא דאמרי להא שמעתא הכי",phraseMeaning:"There are those who say this tradition thus"},
{word:"משמע",meaning:"It implies",phrase:" משמע דאמר",phraseMeaning:"It implies that he said"},
{word:"וכו״",meaning:"(וכולי) etc",phrase:"שבת יום טוב חול המועד וכו׳",phraseMeaning:"Sabbath, festival, intermediate festival, and so forth..."},
{word:"שמא",meaning:"Lest perhaps",phrase:" שמא יאמר אדם",phraseMeaning:"Lest a person say"},
{word:"אולם",meaning:"However",phrase:"אולם צריך עיון במה שכתב הרמב״ם",phraseMeaning:"However what the Rambam wrote requires examination"},
{word:"יותר מזה",meaning:"More than this",phrase:"יותר מזה אפילו במחשבה אסור",phraseMeaning:"More than this even in thought it is forbidden"},
{word:"תנו רבנן",meaning:"Our Rabbis taught",phrase:"תנו רבנן: מצוה לישב בסוכה שבעת ימים",phraseMeaning:"Our Rabbis taught: It is a commandment to dwell in the sukkah seven days"},
{word:"ועוד",meaning:"And another thing",phrase:"ועוד דאפילו לרבי יהודה יש לחלק",phraseMeaning:"And another thing even according to Rabbi Yehuda there is to distinguish"},
{word:"קשיא",meaning:"Difficult",phrase:"קשיא דרבי עקיבא אדרבי עקיבא",phraseMeaning:"Rabbi Akiva's [statement] is difficult against Rabbi Akiva's [other statement]"},
{word:"מאי שנא",meaning:"What is different?",phrase:"מאי שנא ראשונה ממאי שנא אחרונה?",phraseMeaning:"What is different about the first one what is different about the last one?"},
{word:"שכתב",meaning:"As he wrote",phrase:"שכתב הרמב״ם בהלכות תשובה",phraseMeaning:"As the Rambam wrote in the Laws of Repentance"},
{word:"מאי טעמא",meaning:"What is the reason?",phrase:"מאי טעמא דרבי יוסי?",phraseMeaning:"What is Rabbi Yosi's reasoning?"},
{word:"קליפות",meaning:"Husks",phrase:"בירור הקליפות הוא עבודת האדם",phraseMeaning:"The refinement of the husks is man's work"},
{word:"אין סוף",meaning:"Without End",phrase:"האור העליון שבאין סוף ברוך הוא",phraseMeaning:"The supernal light that is in the Ein Sof blessed be He"},
{word:"עד ש",meaning:"Until",phrase:"עד שיכוון לבו לשמים",phraseMeaning:"Until he directs his heart to Heaven"},
{word:"כי פליגי",meaning:"Where they disagree",phrase:"כי פליגי בדעת התלמיד",phraseMeaning:"Where they disagree is regarding the student's opinion"},
{word:"כעין",meaning:"Like similar to",phrase:" כעין זה",phraseMeaning:"Something like this"},
{word:"כולי עלמא",meaning:"Everyone (in the conversation)",phrase:"כולי עלמא לא פליגי דאסור",phraseMeaning:"Everyone agrees that it is forbidden"},
{word:"הוה אמינא",meaning:"I would have said",phrase:"הוה אמינא דאפילו בדיעבד נמי לא",phraseMeaning:"I would have said that even after the fact it is also not [permitted]"},
{word:"פלפול",meaning:"Sharp argumentation",phrase:"פלפול בתורה מחדד את השכל",phraseMeaning:"Sharp argumentation in Torah sharpens the intellect"},
{word:"שכ״כ",meaning:"(שכל כך) that (it is) so much",phrase:"אם בחול אסור שכ״כ בשבת",phraseMeaning:"If it is forbidden on weekdays"}
];
