// from rebWords-24nov.csv
let columns = ["RabbinicTerm","Term(English)","PhraseContext","PhraseContext (English)"];
let data = [
{word:"א״א",meaning:"(אי אפשר) Impossible",phrase:"א״א לעשות את זה",phraseMeaning:"It is impossible to do this"},
{word:"א״ע",meaning:"(את עצמו/ה) Itself/oneself",phrase:"חיבק א״ע מרוב שמחה",phraseMeaning:"He hugged himself from joy"},
{word:"אדרבה",meaning:"On the contrary / the opposite",phrase:"אדרבה! מהאי טעמא לא שנא",phraseMeaning:"On the contrary! For this very reason it makes no difference"},
{word:"אהבת השם",meaning:"Love of God",phrase:"העבודה צריכה להיות מתוך אהבת השם ויראתו",phraseMeaning:"Service must be performed out of love of God and fear of Him"},
{word:"אולם",meaning:"However",phrase:"אולם צריך עיון במה שכתב הרמב״ם",phraseMeaning:"However what the Rambam wrote requires examination"},
{word:"אורייתא",meaning:"Aramaic for Torah",phrase:"מילתא דאורייתא היא",phraseMeaning:"It is a matter of Torah law"},
{word:"אז",meaning:"Then",phrase:" אז לא אמר קרא",phraseMeaning:"Then the verse would not have said"},
{word:"אי הכי",meaning:"If so",phrase:"אי הכי אמאי קתני מיחייב?",phraseMeaning:"If so why does it teach that he is liable?"},
{word:"אי נמי",meaning:"Or alternatively",phrase:"אי נמי דאמר רבי יוחנן משום חשדא",phraseMeaning:"Or alternatively that which Rabbi Yochanan said regarding suspicion"},
{word:"דאמרי",meaning:"Who say",phrase:"איכא דאמרי להא שמעתא הכי",phraseMeaning:"There are those who say this tradition thus"},
{word:"איכא",meaning:"There is",phrase:"איכא דאמרי להא שמעתא הכי",phraseMeaning:"There are those who say this tradition thus"},
{word:"איתא",meaning:"There is",phrase:" איתא בברייתא",phraseMeaning:"It is taught in a baraita"},
{word:"איתימא",meaning:"There are those who say",phrase:" איתימא דבר אחר",phraseMeaning:"There are those who say another approach"},
{word:"אלו הן",meaning:"These are them",phrase:" אלו הן דברים שאין להם שיעור",phraseMeaning:"These are the things that have no measure"},
{word:"אלא",meaning:"Rather",phrase:"לא כן אלא כך הוא הדבר",phraseMeaning:"Not so but rather this is how the matter is"},
{word:"אלא מאי",meaning:"But rather what?",phrase:"אלא מאי איכא למימר?",phraseMeaning:"But rather what is there to say?"},
{word:"אמאי",meaning:"Why?",phrase:"אמאי לא אמר רחמנא בהדיא?",phraseMeaning:"Why didn't the Torah state explicitly?"},
{word:"אמנם",meaning:"Indeed",phrase:" אמנם הכא שאני",phraseMeaning:"However here it is different"},
{word:"אין הכי נמי",meaning:"Yes indeed",phrase:"אין הכי נמי דתנן במשנה",phraseMeaning:"Indeed yes for we learned in the Mishnah"},
{word:"אין סוף",meaning:"Without End",phrase:"האור העליון שבאין סוף ברוך הוא",phraseMeaning:"The supernal light that is in the Ein Sof blessed be He"},
{word:"אך",meaning:"But",phrase:"אך צריך להבין הטעם לחילוק זה",phraseMeaning:"But one needs to understand the reason for this distinction"},
{word:"אסור",meaning:"Forbidden",phrase:"אסור לאדם שיקדים תפילתו לנץ החמה",phraseMeaning:"It is forbidden for a person to advance his prayer before sunrise"},
{word:"אע״פ",meaning:"(אף על פי) Even though",phrase:"אע״פ כן צריך לברך עליו",phraseMeaning:" Even though this is so one needs to recite a blessing over it"},
{word:"בבחי׳",meaning:"(בבחינת) In the aspect of",phrase:"בבחינת מצוה ",phraseMeaning:" In the aspect or quality of a Mitzvah"},
{word:"בענין",meaning:"Regarding the matter of",phrase:"בענין קריאת שמע יש לדעת",phraseMeaning:"Regarding the matter of reciting the Shema one should know"},
{word:"בו״ד",meaning:"(בשר ודם) Flesh and blood (eg human)",phrase:"היא רק בו״ד",phraseMeaning:"She is only human"},
{word:"בודאי",meaning:"Certainly",phrase:"בודאי שהדבר צריך יון נוסף",phraseMeaning:"Certainly this matter requires further examination"},
{word:"בירור",meaning:"Clarification/refinement",phrase:"בירור הניצוצות הוא עיקר עבודתו של האדם",phraseMeaning:"The refinement of the sparks is the essence of man's service"},
{word:"בנ״י",meaning:"(בני ישראל) Children of Israel",phrase:"כאשר יצאו בנ״י ממצרים",phraseMeaning:"When the Children of Israel left Egypt"},
{word:"בקיצור",meaning:"In brief",phrase:"בקיצור כל המצוות תלויות בכוונה",phraseMeaning:"In brief all commandments depend on intention"},
{word:"בשמים",meaning:"In-heaven / Spices",phrase:"לא בשמים היא",phraseMeaning:"It isn't [only] in heaven"},
{word:"בתר",meaning:"After",phrase:" בתר רבים אזלינן",phraseMeaning:"We follow the majority"},
{word:"תנא",meaning:"(Early period) teacher",phrase:"תנא בתרא הוא דאתא לאפוקי",phraseMeaning:"It is the last Tanna that he comes to exclude / ...Tanna that comes to exclude it"},
{word:"לאפוקי",meaning:"To exclude",phrase:"תנא בתרא הוא דאתא לאפוקי",phraseMeaning:"It is the last Tanna that he comes to exclude / ...Tanna that comes to exclude it"},
{word:"אתא",meaning:"He/it came",phrase:"תנא בתרא הוא דאתא לאפוקי",phraseMeaning:"It is the last Tanna that he comes to exclude / ...Tanna that comes to exclude it"},
{word:"בתרא",meaning:"The last",phrase:"תנא בתרא הוא דאתא לאפוקי",phraseMeaning:"It is the last Tanna that he comes to exclude / ...Tanna that comes to exclude it"},
{word:"ג״כ",meaning:"(גם כן) Also",phrase:"הדין נוהג בגוים ג״כ",phraseMeaning:"This law applies to non-Jews as well"},
{word:"גופא",meaning:"Itself",phrase:" גופא קשיא",phraseMeaning:"The matter itself is difficult"},
{word:"גמרא",meaning:"Gemara",phrase:"גמרא: מנא הני מילי?",phraseMeaning:"The Gemara asks: From where do we derive these matters?"},
{word:"גרידא",meaning:"Only/merely",phrase:" הלכה גרידא",phraseMeaning:"Merely a law"},
{word:"גרסינן",meaning:"This is the version that we use",phrase:" הכי גרסינן",phraseMeaning:"Thus we learn (ie., we use this version) "},
{word:"דבקות",meaning:"Cleaving to God",phrase:"הדבקות הוא שורש כל העבודה",phraseMeaning:"Cleaving [to God] is the root of all service"},
{word:"דווקא",meaning:"Precisely/specifically",phrase:"דווקא בשבת צריך להוסיף בקדושה",phraseMeaning:"Specifically on Shabbat one needs to add in sanctity"},
{word:"דומיא",meaning:"Similar to",phrase:" דומיא דסוכה",phraseMeaning:"Similar to a sukkah"},
{word:"דוחה",meaning:"Push off take precedence over",phrase:" פיקוח נפש דוחה שבת",phraseMeaning:"Saving life overrides the Sabbath"},
{word:"דמי",meaning:"It is similar to",phrase:"הא דמי להא דאמרינן בפרק קמא",phraseMeaning:"This is similar to what we said in the first chapter"},
{word:"הא",meaning:"This/Behold",phrase:" הא לן והא להו",phraseMeaning:"This applies to us and that to them"},
{word:"הא !?",meaning:"Is it not",phrase:" הא תניא אידך",phraseMeaning:"But wasn't it taught otherwise? / Behold, another one taught (as follows)?"},
{word:"מיפטרי",meaning:"Parting, separating, making exempt",phrase:"כי הוו מיפטרי מהדדי",phraseMeaning:"When they were (de)parting from one another"},
{word:"הדדי",meaning:"One another",phrase:"כי הוו מיפטרי מהדדי",phraseMeaning:"When they were (de)parting from one another"},
{word:"הוה אמינא",meaning:"I would have said",phrase:"הוה אמינא דאפילו בדיעבד נמי לא",phraseMeaning:"I would have said that even after the fact it is also not [permitted]"},
{word:"הוו יתבי",meaning:"They were sitting",phrase:" הוו יתבי רבנן וקא בעו",phraseMeaning:"The rabbis were sitting and asking"},
{word:"הואיל",meaning:"Since",phrase:" הואיל וטמא טמא",phraseMeaning:"Since he declared it (or somehow made it) impure, it is (thus) impure"},
{word:"הכי",meaning:"Thus",phrase:"הכי גרסינן במתניתא",phraseMeaning:"This is how we learn it in the Mishnah"},
{word:"הכי נמי",meaning:"It is really so",phrase:"הכי נמי דאמר רב אשי",phraseMeaning:"It is really as Rav Ashi said"},
{word:"הכא",meaning:"Here",phrase:" הכא במאי עסקינן",phraseMeaning:"What are we dealing with here?"},
{word:"הלכתא",meaning:"(Aramaic) The law",phrase:"הלכתא כוותיה דרבי יהושע",phraseMeaning:"The law follows Rabbi Yehoshua"},
{word:"ההוא",meaning:"That one",phrase:"ההוא דאמר רבא בפרק בתרא",phraseMeaning:"That which Rava said in the last chapter"},
{word:"הספיק",meaning:"Have enough have enough time",phrase:" הספיק לעשות",phraseMeaning:"There was enough time to do it"},
{word:"הקדוש ברוך הוא",meaning:"The Holy One Blessed be He",phrase:"הקדוש ברוך הוא בורא כל יום מעשה בראשית",phraseMeaning:"The Holy One Blessed be He creates anew each day the work of creation"},
{word:"הקשו",meaning:"They raised a question; they found a difficulty",phrase:" הקשו תלמידיו",phraseMeaning:"His students asked"},
{word:"התבודדות",meaning:"Secluded meditation",phrase:"התבודדות בשדה היא דרך חשובה בעבודת השם",phraseMeaning:"Secluded meditation in the field is an important way in the service of God"},
{word:"התם",meaning:"There",phrase:" התם איכא למימר",phraseMeaning:"There one can say"},
{word:"היאך",meaning:"How?",phrase:"היאך אפשר לקיים מצווה זו כהלכתה?",phraseMeaning:"How is it possible to fulfill this commandment according to its law?"},
{word:"היינו",meaning:"Is equal to; that is",phrase:" היינו דאמר רבא",phraseMeaning:"This is the same as what Rava said"},
{word:"היכא",meaning:"Where",phrase:" היכא דאיכא",phraseMeaning:"Where there is"},
{word:"ואי בעית אימא",meaning:"And if you wish say",phrase:"ואי בעית אימא מהאי קרא דכתיב",phraseMeaning:"And if you wish say [it is derived] from this verse. As it is written..."},
{word:"ודאי",meaning:"Certain",phrase:"ספק וודאי ודאי עדיף",phraseMeaning:"Between doubt and certainty certainty is preferable"},
{word:"וגו׳",meaning:"(וגומר) and so on",phrase:"כסף זהב סוסים וגו׳ ",phraseMeaning:"Silver, gold, horses, and so forth..."},
{word:"וכו״",meaning:"(וכולי) etc",phrase:"שבת יום טוב חול המועד וכו׳",phraseMeaning:"Sabbath, festival, intermediate festival, and so forth..."},
{word:"ולא עוד אלא ",meaning:"Not only that but (also) ",phrase:"ולא עוד אלא אסור",phraseMeaning:"Not only that but (also) it is forbidden"},
{word:"ומי איכא",meaning:"And is there?",phrase:"ומי איכא ספיקא קמי שמיא",phraseMeaning:"And is there doubt before Heaven?"},
{word:"ועוד",meaning:"And another thing",phrase:"ועוד דאפילו לרבי יהודה יש לחלק",phraseMeaning:"And another thing even according to Rabbi Yehuda there is to distinguish"},
{word:"ותו",meaning:"And furthermore; and more",phrase:"ותו לא והא קמ״ל",phraseMeaning:"And no more!? But behold, it comes to teach..."},
{word:"וזה לשון",meaning:"And this is the language of",phrase:"וזה לשון הגמרא שם",phraseMeaning:"And this is the language of the Gemara there"},
{word:"ח״ו",meaning:"(חס וחלילה / חס ושלום) God forbid",phrase:"אל יחשוב אדם מחשבות רעות ח״ו",phraseMeaning:"A person should not think evil thoughts"},
{word:"חידוש",meaning:"Novel interpretation",phrase:"חידוש גדול חידש לנו הבעש״ט",phraseMeaning:"The Ba'al Shem Tov innovated a great novel teaching for us"},
{word:"חייב",meaning:"Obligated/liable",phrase:"חייב אדם לברך מאה ברכות בכל יום",phraseMeaning:"A person is obligated to recite one hundred blessings every day"},
{word:"חז״ל",meaning:"(חכמינו זכרונם לברכה) Our Sages of blessed memory",phrase:"כמאמר חז״ל גדול השלום",phraseMeaning:"As our Sages said 'Great is peace"},
{word:"חשאי",meaning:"Secret",phrase:" במילי דחשאי",phraseMeaning:"In matters that are private/secret"},
{word:"י״ל",meaning:"(יש לומר) there is to say",phrase:"על פסוק זה י״ל שני פירושים",phraseMeaning:"Regarding this verse"},
{word:"יחוד",meaning:"Unification",phrase:"יחוד השם הוא תכלית כל המצוות",phraseMeaning:"The unification of God's name is the purpose of all commandments"},
{word:"יותר מזה",meaning:"More than this",phrase:"יותר מזה אפילו במחשבה אסור",phraseMeaning:"More than this even in thought it is forbidden"},
{word:"יראת שמים",meaning:"Fear of Heaven",phrase:"יראת שמים קודמת לחכמה",phraseMeaning:"Fear of Heaven precedes wisdom"},
{word:"כאמור",meaning:"As it is said",phrase:"כאמור בגמרא דידן",phraseMeaning:"As it is said in our Gemara"},
{word:"כביכול",meaning:"As it were / If it were possible",phrase:" כביכול נס",phraseMeaning:"A miracle, as it were"},
{word:"כגון",meaning:"For example",phrase:"כגון תפילין ומזוזה ומצוות אחרות",phraseMeaning:"For example tefillin and mezuzah and other commandments"},
{word:"כדי",meaning:"So that",phrase:" כדי שיהא",phraseMeaning:"In order that it should be"},
{word:"כולי עלמא",meaning:"Everyone (in the conversation)",phrase:"כולי עלמא לא פליגי דאסור",phraseMeaning:"Everyone agrees that it is forbidden"},
{word:"כוונה",meaning:"Intention",phrase:"כוונה היא חיות התפילה",phraseMeaning:"Intention is the vitality of prayer"},
{word:"כעין",meaning:"Like similar to",phrase:" כעין זה",phraseMeaning:"Something like this"},
{word:"כי פליגי",meaning:"Where they disagree",phrase:"כי פליגי בדעת התלמיד",phraseMeaning:"Where they disagree is regarding the student's opinion"},
{word:"כיון",meaning:"Since",phrase:"כיון דכתיב קרא הכי",phraseMeaning:"Since the verse is written thus"},
{word:"כיצד",meaning:"How so?",phrase:"כיצד מברכים ברכת המזון?",phraseMeaning:"How does one recite the Grace After Meals?"},
{word:"כלומר",meaning:"That is to say, in other words",phrase:" כלומר הכי קאמר",phraseMeaning:"In other words: this is what they/it says"},
{word:"כנ״ל",meaning:"(כנזכר לעיל כנראה למעלה) As appears/mentioned above",phrase:"הטעם בזה כנ״ל בסימן הקודם",phraseMeaning:"The reason for this is as mentioned in the previous section"},
{word:"כפי ש",meaning:"According to",phrase:"כפי שנתבאר במקום אחר",phraseMeaning:"According to what was explained elsewhere"},
{word:"כש",meaning:"When",phrase:"כשאדם מתפלל צריך לכוון לבו",phraseMeaning:"When a person prays he needs to direct his heart"},
{word:"לא הכי",meaning:"Not so",phrase:"לא הכי אמינא אלא הכי קאמינא",phraseMeaning:"I do not say it that way but rather I say it this way"},
{word:"לא שנא",meaning:"It makes no difference",phrase:"לא שנא איש ואשה בדבר זה",phraseMeaning:"It makes no difference [between] man and woman in this matter"},
{word:"לאו הכי",meaning:"Not so",phrase:"לאו הכי נמי אסור",phraseMeaning:"Not so it is also forbidden"},
{word:"לית",meaning:"(אין) there is not",phrase:"לית דין דמי להאי",phraseMeaning:"There is no law/judgement that is comparable to this one"},
{word:"לימא",meaning:"Let him say",phrase:" לימא כתנאי",phraseMeaning:"Let us say it is like the tannaim"},
{word:"לכאורה",meaning:"It seems at first glance",phrase:" לכאורה קשיא",phraseMeaning:"Apparently it is difficult"},
{word:"למה הדבר דומה",meaning:"To what is this similar?",phrase:" למה הדבר דומה למלך",phraseMeaning:"What is this comparable to? To a king"},
{word:"לפיכך",meaning:"Therefore",phrase:"לפיכך צריך להזהר בדבר זה",phraseMeaning:"Therefore one needs to be careful in this matter"},
{word:"ליתא",meaning:"There is not",phrase:"הא דקאמר ליתא דהא תנן במשנה",phraseMeaning:"What he says is not so for we learned in the Mishnah"},
{word:"מאן",meaning:"Who",phrase:" מאן תנא",phraseMeaning:"Who taught this?"},
{word:"מאי טעמא",meaning:"What is the reason?",phrase:"מאי טעמא דרבי יוסי?",phraseMeaning:"What is Rabbi Yosi's reasoning?"},
{word:"מאי שנא",meaning:"What is different?",phrase:"מאי שנא ראשונה ממאי שנא אחרונה?",phraseMeaning:"What is different about the first one what is different about the last one?"},
{word:"מה — אף",meaning:"Just as — so also",phrase:" מה שם כך אף כאן",phraseMeaning:"Just as there, so also here"},
{word:"מה לי",meaning:"What's it to me? What difference to me",phrase:" מה לי זה ומה לי זה",phraseMeaning:"What difference is there between this and that?"},
{word:"מידי",meaning:"Something like",phrase:"מידי דהוה אכל הנך דרבנן",phraseMeaning:"Something like all those [cases] of the Rabbis"},
{word:"מיבעי ליה",meaning:"He needs",phrase:" מיבעי ליה לכדרבי",phraseMeaning:"He needs it for [to be consistent with] Rabbi's teaching"},
{word:"מילתא",meaning:"RabbinicTerm thing affair",phrase:" מילתא דלא שכיחא",phraseMeaning:"Something that is uncommon"},
{word:"ממילא",meaning:"Consequently",phrase:"ממילא פטור מכל המצוות",phraseMeaning:"Consequently he is exempt from all commandments"},
{word:"ממש",meaning:"Actually/literally",phrase:"ממש כפשוטו של מקרא",phraseMeaning:"Actually according to the simple meaning of the verse"},
{word:"מ״מ",meaning:"(מכל מקום) In any case",phrase:"אף שיש ספק בדבר מ״מ יש להחמיר",phraseMeaning:"Even though there is doubt in the matter"},
{word:"מנא",meaning:"From where?",phrase:"מנא לן דבעי כוונה?",phraseMeaning:"From where do we [know] that intention is required?"},
{word:"מנה״מ",meaning:"(מנא הני מילי) where did these words come from? what is the source?",phrase:"מנה״מ? אמר רב יהודה",phraseMeaning:"From where do we derive these matters? Rav Yehuda said"},
{word:"מנין",meaning:"Prayer quorum",phrase:"אין מתחילין בברכות אלא במנין",phraseMeaning:"We do not begin with blessings except with a minyan"},
{word:"מר",meaning:"The Master",phrase:" אמר מר",phraseMeaning:"The master said"},
{word:"מסקנא",meaning:"The conclusion",phrase:"מסקנא דמילתא הכי הוא",phraseMeaning:"The conclusion of the matter is thus"},
{word:"מציעתא",meaning:"The middle part",phrase:"מציעתא דמתניתא קא מיירי",phraseMeaning:"The middle part of the Mishnah is what we are dealing with"},
{word:"מצווה",meaning:"Commandment / good-deed",phrase:"מצווה הבאה בעבירה",phraseMeaning:"A good-deed that comes via a transgression"},
{word:"משא״כ",meaning:"(מה שאין כן) Which is not the case",phrase:"בשבת אסור לעשות מלאכה משא״כ בחול",phraseMeaning:"On Sabbath it is forbidden to do work"},
{word:"משום הכי",meaning:"Because of this",phrase:"משום הכי אמר רחמנא",phraseMeaning:"Because of this the Torah said"},
{word:"משמע",meaning:"It implies",phrase:" משמע דאמר",phraseMeaning:"It implies that he said"},
{word:"מותר",meaning:"Permitted",phrase:"מותר לעשות מלאכה זו בשבת",phraseMeaning:"It is permitted to do this work on Shabbat"},
{word:"נמי",meaning:"Also",phrase:" אף על גב דנמי",phraseMeaning:"Even though also"},
{word:"נפקא מנה",meaning:"What come out from it practical result",phrase:" נפקא מנה תלת",phraseMeaning:"Three things derive from it"},
{word:"סטרא אחרא",meaning:"The Other [wild/evil] Side",phrase:" מסטרא אחרא זה",phraseMeaning:"This is from the other perspective"},
{word:"סיפא",meaning:"The end",phrase:"סיפא דמתניתא משמע דאסור",phraseMeaning:"The end of the Mishnah implies that it is forbidden"},
{word:"סוף דבר",meaning:"The conclusion",phrase:"סוף דבר הכל צפוי והרשות נתונה",phraseMeaning:"The conclusion is everything is foreseen yet free will is given"},
{word:"סוף מילתא",meaning:"The final word",phrase:"סוף מילתא דכולי עלמא לא פליגי",phraseMeaning:"The final word is that everyone agrees they do not disagree"},
{word:"ספירות",meaning:"Divine emanations",phrase:"עשר ספירות בלימה הן יסוד כל הבריאה",phraseMeaning:"Ten sefirot without substance are the foundation of all creation"},
{word:"ספק",meaning:"Doubt",phrase:"ספק ברכות להקל",phraseMeaning:"In case of doubt regarding blessings rule leniently"},
{word:"עבודה",meaning:"Service",phrase:"עבודה שבלב זו תפילה",phraseMeaning:"The service that is in the heart that is prayer"},
{word:"עד ש",meaning:"Until",phrase:"עד שיכוון לבו לשמים",phraseMeaning:"Until he directs his heart to Heaven"},
{word:"עוה״ז",meaning:"(עולם הזה) this world",phrase:"מצוות נתנו ליהנות בעוה״ז",phraseMeaning:"Commandments were given to be enjoyed in this world"},
{word:"עוה״ב",meaning:"(עולם הבא) the next world",phrase:"צדיקים זוכים לחיי עוה״ב",phraseMeaning:"The righteous merit life in the world to come"},
{word:"על אחת כמה וכמה",meaning:"All the more so",phrase:" מקל וחומר על אחת כמה וכמה",phraseMeaning:"From a minor to major inference"},
{word:"על פי",meaning:"According to",phrase:"על פי הדברים האלה כרתי אתכם ברית",phraseMeaning:"According to these words I have made a covenant with you"},
{word:"על ידי",meaning:"Through",phrase:" על ידי דבר זה",phraseMeaning:"By means of this thing"},
{word:"עי״ז",meaning:"(על ידי זה) through this",phrase:"עי״ז יכול האדם להתקדש",phraseMeaning:"Through this a person can become sanctified"},
{word:"עניין",meaning:"The matter of",phrase:"עניין התפילה הוא עיקר עבודת השם",phraseMeaning:"The matter of prayer is the essence of serving God"},
{word:"פירוש",meaning:"Explanation",phrase:"פירוש רש״י הוא הפירוש המקובל",phraseMeaning:"Rashi's explanation is the accepted explanation"},
{word:"פלפול",meaning:"Sharp argumentation",phrase:"פלפול בתורה מחדד את השכל",phraseMeaning:"Sharp argumentation in Torah sharpens the intellect"},
{word:"פליג",meaning:"Argue",phrase:" פליג עליה",phraseMeaning:"He disagrees with him"},
{word:"פסול",meaning:"Disqualified",phrase:" פסול ועושה",phraseMeaning:"Invalid but usable"},
{word:"פטור",meaning:"Exempt",phrase:"פטור מן התפילה בעת הדחק",phraseMeaning:"Exempt from prayer in times of distress"},
{word:"פרש״י",meaning:"(פרוש רש״י) Rashi's commentary",phrase:"כמו שפירש פרש״י על המקרא",phraseMeaning:"As Rashi explained on the biblical verse"},
{word:"צדיק",meaning:"Righteous person",phrase:"צדיק באמונתו יחיה",phraseMeaning:"The righteous person lives by his faith"},
{word:"קליפות",meaning:"Husks",phrase:"בירור הקליפות הוא עבודת האדם",phraseMeaning:"The refinement of the husks is man's work"},
{word:"קמא",meaning:"The first",phrase:"תנא קמא סבר כרבי מאיר",phraseMeaning:"The first Tanna holds like Rabbi Meir"},
{word:"קל וחומר",meaning:"All the more so",phrase:"ומה שבת שמותרת בפיקוח נפש קל וחומר בחג",phraseMeaning:"And if Shabbat which is permitted for saving life all the more so on a festival"},
{word:"קשיא",meaning:"Difficult",phrase:"קשיא דרבי עקיבא אדרבי עקיבא",phraseMeaning:"Rabbi Akiva's [statement] is difficult against Rabbi Akiva's [other statement]"},
{word:"רמי",meaning:"Throw a contradiction or a challenge",phrase:" רמי בר חמא",phraseMeaning:"Bar Chama raised an objection"},
{word:"רבונו של עולם",meaning:"Master of the Universe",phrase:"רבונו של עולם מלא כל הארץ כבודו",phraseMeaning:"Master of the Universe the whole earth is full of His glory"},
{word:"רישא",meaning:"The beginning/top",phrase:"רישא דמתניתא קתני הכי",phraseMeaning:"The beginning of the Mishnah teaches thus"},
{word:"שאני",meaning:"It is different",phrase:"שאני התם דכתיב קרא",phraseMeaning:"That case is different because a verse is written"},
{word:"שאני הכא",meaning:"This case is different",phrase:"שאני הכא דאיכא למימר",phraseMeaning:"This case is different because there is to say"},
{word:"שכינה",meaning:"Divine Presence",phrase:"שכינה שורה על עשרה היושבים ועוסקים בתורה",phraseMeaning:"The Divine Presence rests upon ten who sit and occupy themselves with Torah"},
{word:"שכ״כ",meaning:"(שכל כך) that (it is) so much",phrase:"אם בחול אסור שכ״כ בשבת",phraseMeaning:"If it is forbidden on weekdays"},
{word:"שכתב",meaning:"As he wrote",phrase:"שכתב הרמב״ם בהלכות תשובה",phraseMeaning:"As the Rambam wrote in the Laws of Repentance"},
{word:"שמא",meaning:"Lest perhaps",phrase:" שמא יאמר אדם",phraseMeaning:"Lest a person say"},
{word:"שמע מנה",meaning:"Hear from this infer from this",phrase:" שמע מנה תלת",phraseMeaning:"Learn three things from this"},
{word:"שנאמר",meaning:"As it is written",phrase:"שנאמר והיה ה׳ למלך על כל הארץ",phraseMeaning:"As it is written 'And the Lord shall be King over all the earth'"},
{word:"ש״ק",meaning:"(שבת קודש) Holy Sabbath",phrase:"בליל ש״ק נהגו לעשות סעודה",phraseMeaning:"On the eve of the holy Sabbath it was customary to make a meal"},
{word:"שטות",meaning:"Nonsense stupidity",phrase:" שטות היא זו",phraseMeaning:"This is nonsense"},
{word:"תימה",meaning:"Astonishing",phrase:"תימה היאך אפשר דבר זה",phraseMeaning:"It's astonishing how such a thing is possible"},
{word:"תיקו",meaning:"Let it stand [unresolved]",phrase:"תיקו עד שיבא אליהו ויתרץ כל הקושיות",phraseMeaning:"Let it stand until Elijah comes and resolves all difficulties"},
{word:"תיקון",meaning:"Repair/rectification",phrase:"תיקון עולם במלכות שדי",phraseMeaning:"The rectification of the world under the sovereignty of the Almighty"},
{word:"תלמוד לומר",meaning:"A scriptural source teaches / A (biblical) teaching says",phrase:" תלמוד לומר אחר",phraseMeaning:"The verse teaches by saying 'other'"},
{word:"תורה לשמה",meaning:"Torah for its own sake",phrase:"גדולה תורה לשמה שמביאה לידי מעשה",phraseMeaning:"Great is Torah studied for its own sake for it leads to action"},
{word:"תנו רבנן",meaning:"Our Rabbis taught",phrase:"תנו רבנן: מצוה לישב בסוכה שבעת ימים",phraseMeaning:"Our Rabbis taught: It is a commandment to dwell in the sukkah seven days"}
];
